### yyspace docker-compose for services
version: "3.2"

services:
######################################################
### db_elastic container
######################################################
  db_elastic:
    image: elastic:6.0.0
    container_name: ${ELASTIC_NAME}
    hostname: ${ELASTIC_NAME}
    environment:
      - TAKE_FILE_OWNERSHIP=true
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - ELASTIC_PASSWORD=elastic
    networks:
      - yynet
    ports:
      - "${ELASTIC_HTTP_PORT}:9200"
      - "${ELASTIC_TCP_PORT}:9300"
    privileged: true
    #sysctls:
    #  - "vm.max_map_count=262144"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./data/elastic
        target: /usr/share/elasticsearch/data
        propagation: "rpublic"

networks:
  yynet:
