### docker-compose for services
version: "3.2"

services:
  db_mysql:
    container_name: db_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    image: mysql/mysql-server:latest
    networks:
      - net_one
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: data_mysql
        target: /var/lib/mysql
        volume:
          nocopy: true
      #- type: volume
      #  source: data_mysql/my.cnf
      #  target: /etc/my.cnf
      #  volume:
      #    nocopy: true

volumes:
  data_mysql:

networks:
  net_one:
