### docker-compose for mesos-master cluster
version: "3.2"

services:
  svr_mesoss1:
    container_name: svr_mesoss1
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: zk://svr_zk1:2181,svr_zk2:2181,svr_zk3:2181/mesos
      MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker
      #MESOS_DOCKER_STOP_TIMEOUT: 200000
      #MESOS_EXEUTOR_REGISTRATION_TIMEOUT: 500000
    hostname: svr_mesoss1
    image: mesoscloud/mesos-slave:latest
    networks:
      - net_test
    ports:
      - "6051:5051"
    volumes:
      - "/etc/docker:/etc/docker"
      - "/tmp/log/mesos:/var/log/mesos"
      - "/tmp/mesos:/tmp/mesos"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys:/sys"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/lib64/libsystemd.so.0:/lib/libsystemd.so.0"
      - "/lib64/libselinux.so.1:/lib/libselinux.so.1"
      - "/lib64/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02"
      - "/lib64/libgcrypt.so.20:/lib/libgcrypt.so.20"
  
  svr_mesoss2:
    container_name: svr_mesoss2
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: zk://svr_zk1:2181,svr_zk2:2181,svr_zk3:2181/mesos
      #MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker
      #MESOS_DOCKER_STOP_TIMEOUT: 200000
      #MESOS_EXEUTOR_REGISTRATION_TIMEOUT: 500000
    hostname: svr_mesoss2
    image: mesoscloud/mesos-slave:latest
    networks:
      - net_test
    ports:
      - "6052:5051"
    volumes:
      - "/etc/docker:/etc/docker"
      - "/tmp/log/mesos:/var/log/mesos"
      - "/tmp/mesos:/tmp/mesos"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys:/sys"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/lib64/libsystemd.so.0:/lib/libsystemd.so.0"
      - "/lib64/libselinux.so.1:/lib/libselinux.so.1"
      - "/lib64/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02"
      - "/lib64/libgcrypt.so.20:/lib/libgcrypt.so.20"

  svr_mesoss3:
    container_name: svr_mesoss3
    environment:
      MESOS_PORT: 5051
      MESOS_MASTER: zk://svr_zk1:2181,svr_zk2:2181,svr_zk3:2181/mesos
      #MESOS_SWITCH_USER: 0
      MESOS_CONTAINERIZERS: docker
      #MESOS_DOCKER_STOP_TIMEOUT: 200000
      #MESOS_EXEUTOR_REGISTRATION_TIMEOUT: 500000
    hostname: svr_mesoss3
    image: mesoscloud/mesos-slave:latest
    networks:
      - net_test
    ports:
      - "6053:5051"
    volumes:
      - "/etc/docker:/etc/docker"
      - "/tmp/log/mesos:/var/log/mesos"
      - "/tmp/mesos:/tmp/mesos"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/sys:/sys"
      - "/usr/bin/docker:/usr/bin/docker"
      - "/lib64/libsystemd.so.0:/lib/libsystemd.so.0"
      - "/lib64/libselinux.so.1:/lib/libselinux.so.1"
      - "/lib64/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02"
      - "/lib64/libgcrypt.so.20:/lib/libgcrypt.so.20"

#volumes:

networks:
  net_test:
