### docker-compose for services
version: "3.2"

services:
  svr_zk1:
    container_name: svr_zk1
    environment:
      ZOO_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=svr_zk1:2888:3888 server.2=svr_zk2:2888:3888 server.3=svr_zk3:2888:3888
    hostname: svr_zk1
    image: zookeeper:latest
    networks:
      - net_test
    ports:
      - "2181:2181"
    volumes:
      - type: volume
        source: data_zk1_conf
        target: /conf
       # volume:
       #   nocopy: true
      - type: volume
        source: data_zk1_data
        target: /data
        volume:
          nocopy: true
      - type: volume
        source: data_zk1_log
        target: /datalog
        volume:
          nocopy: true
  
  svr_zk2:
    container_name: svr_zk2
    environment:
      ZOO_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=svr_zk1:2888:3888 server.2=svr_zk2:2888:3888 server.3=svr_zk3:2888:3888
    hostname: svr_zk2
    image: zookeeper:latest
    networks:
      - net_test
    ports:
      - "2182:2181"
    volumes:
      - type: volume
        source: data_zk2_conf
        target: /conf
       # volume:
       #   nocopy: true
      - type: volume
        source: data_zk2_data
        target: /data
        volume:
          nocopy: true
      - type: volume
        source: data_zk2_log
        target: /datalog
        volume:
          nocopy: true

  svr_zk3:
    container_name: svr_zk3
    environment:
      ZOO_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=svr_zk1:2888:3888 server.2=svr_zk2:2888:3888 server.3=svr_zk3:2888:3888
    hostname: svr_zk3
    image: zookeeper:latest
    networks:
      - net_test
    ports:
      - "2183:2181"
    volumes:
      - type: volume
        source: data_zk3_conf
        target: /conf
       # volume:
       #   nocopy: true
      - type: volume
        source: data_zk3_data
        target: /data
        volume:
          nocopy: true
      - type: volume
        source: data_zk3_log
        target: /datalog
        volume:
          nocopy: true

volumes:
  data_zk1_conf:
  data_zk1_data:
  data_zk1_log:
  data_zk2_conf:
  data_zk2_data:
  data_zk2_log:
  data_zk3_conf:
  data_zk3_data:
  data_zk3_log:

networks:
  net_test:
