### yyspace docker-compose for services
version: "3.2"

services:
######################################################
### db-elastic container
######################################################
  db-elastic:
    container_name: ${ELASTIC_NAME}
    environment:
      - cluster.name=es-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx512m"
    hostname: ${ELASTIC_NAME}
    image: elastic:6.0.0
    networks:
      - xnet
    ports:
      - "${ELASTIC_HTTP_PORT}:9200"
      - "${ELASTIC_TCP_PORT}:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: bind
        source: ./data/elastic
        target: /usr/share/elasticsearch/data

networks:
  xnet:
