### yyspace docker-compose for services
version: "3.2"

services:
######################################################
### srv-zookeeper container
######################################################
  srv-zookeeper:
    container_name: ${ZOOKEEPER_NAME}
    environment:
      ZOO_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=${ZOOKEEPER_NAME}:2888:3888
    hostname: ${ZOOKEEPER_NAME}
    image: zookeeper:latest
    networks:
      - xnet
    ports:
      - "${ZOOKEEPER_PORT}:2181"
    volumes:
      - type: bind
        source: ./conf/zookeeper
        target: /conf
      - type: bind
        source: ./data/zk/data
        target: /data
      - type: bind
        source: ./data/zk/datalog
        target: /datalog

#volumes:
#  v_zk_conf:

networks:
  xnet:
