### yyspace docker-compose for services
version: "3.2"

services:
######################################################
### srv_zk container
######################################################
  srv_zk:
    container_name: ${ZK_NAME}
    environment:
      ZOO_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=${ZK_NAME}:2888:3888
    hostname: ${ZK_NAME}
    image: zookeeper:latest
    networks:
      - xnet
    ports:
      - "${ZK_PORT}:2181"
    volumes:
      - type: volume
        source: v_zk_conf
        target: /conf
       # volume:
       #   nocopy: true
      - type: bind
        source: ./data/zk/data
        target: /data
      - type: bind
        source: ./data/zk/datalog
        target: /datalog

volumes:
  v_zk_conf:

networks:
  xnet:
