### docker-compose for services
version: "3.2"

services:
  srv_zkui:
    container_name: ${ZKUI_NAME}
    hostname: ${ZKUI_NAME}
    image: zkui:2.0-SNAPSHOT
    networks:
      - yynet
    ports:
      - "${ZKUI_PORT}:9090"
    volumes:
      - ./conf/zkui.cfg:/var/app/config.cfg
    depends_on:
      - srv_zk1
      - srv_zk2
      - srv_zk3

  srv_zk1:
    container_name: ${ZK1_NAME}
    hostname: ${ZK1_NAME}
    image: zookeeper:latest
    environment:
      ZOO_PORT: 2181
      ZOO_TICK_TIME: 2000
      ZOO_INIT_LIMIT: 5
      ZOO_SYNC_LIMIT: 2
      ZOO_MAX_CLIENT_CNXNS: 60
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zk1:2888:3888
      SERVER_JVMFLAGS: -Xms128m -Xmx128m -Xmn64m -XX:SurvivorRatio=4
    networks:
      - yynet
    ports:
      - "${ZK1_PORT}:2181"
    volumes:
      - ./data/zk1:/data
      - ./data/zk1:/datalog
  

networks:
  yynet:
